name: todo-app-CI
on: [push,workflow_dispatch]
env:
  APP_NAME: 'todo-app'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: QualiSystemsLab/colony-validate-bp-action@v0.0.1
      with:
        space: Trial
        files_list: blueprints/todo-app.yaml
        colony_token: ${{ secrets.colony_TOKEN }}
  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo $TAG
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push
  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print result URL
        run: echo "$GITHUB_RUN_ID"
      - name: Start colony Sandbox
        id: start-sandbox
        uses: QualiSystemsLab/colony-start-sb-action@v0.0.1
        with:
          space: Trial
          blueprint_name: todo-app
          colony_token: ${{ secrets.colony_TOKEN }}
          duration: 60
          timeout: 10
          inputs: version=${{ github.event.inputs.version}}

      - name: Test link status code
        run: curl -I $(echo "${{ steps.start-sandbox.outputs.sandbox_shortcuts }}" | grep -o 'http.*' | head -c-4) | grep 200
      - name: Stop sandbox
        uses: QualiSystemsLab/colony-end-sb-action@v0.0.1
        with:
          space: Trial
          sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
          colony_token: ${{ secrets.colony_TOKEN }}
  publish:
    needs: integration-test
    runs-on: ubuntu-latest
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "TAG=latest" >> $GITHUB_ENV
      - run: echo $TAG
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push